spring.application.name=mini-quora

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

info.app.name=${spring.application.name}
info.app.description=A compact question-and-answer application
info.app.java.version=${java.version}

server.error.include-message=never
server.error.include-stacktrace=never
