spring.application.name=machine-coding-api

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

info.app.name=${spring.application.name}
info.app.description=Reusable Spring Boot starter for machine-coding exercises
info.app.java.version=${java.version}

server.error.include-message=never
server.error.include-stacktrace=never
